name: 'C++ CI'

on:
  push:
    branches:
      - master
      - feature/github_actions

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - run: sudo apt-get update && sudo apt-get install libboost-test-dev -y
      - run: cmake -S ./src -B build -DPATCH_VERSION=${{ github.run_number }}
      - run: cmake --build build
      - run: cmake -S ./src/lib -B build_lib -DCMAKE_INSTALL_PREFIX=install
      - run: cmake --build build_lib --target install
      - run: cmake -S ./tests -B build_tests
      - run: cmake --build build_tests
      - run: ctest --test-dir build_tests
      - run: cmake --build ./build --target package
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.run_number }}
          release_name: Release ${{ github.run_number }}
          draft: false
          prerelease: false
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/ip-filter-cli-0.0.${{ github.run_number }}-Linux.deb
          asset_name: ip-filter-cli-0.0.${{ github.run_number }}-Linux.deb
          asset_content_type: application/vnd.debian.binary-package